# Lectura de los archivos scimago desde 1999 hasta 2018

El obejetivo de este código es leer que journals han sido q1 y q2

### 1. Importar librerias

In [1]:
from os import listdir
from os.path import isfile, join
import glob
import pandas as pd

El siguiente comando de pandas hace que se muestren todos los encabezados de los df del archivo.

In [2]:
pd.set_option('display.max_columns', None)

### 2.  Lista de archivos en la carpeta

Esta opción lee los nombres de archivos en una lista y los almacena en una lista

In [3]:
pathf = r'00_scimago_rank'
onlyfiles = [f for f in listdir(pathf) if isfile(join(pathf, f))]

In [4]:
onlyfiles

['Leame.docx',
 'scimagojr 1999  Subject Category - Finance.csv',
 'scimagojr 2000  Subject Category - Finance.csv',
 'scimagojr 2001  Subject Category - Finance.csv',
 'scimagojr 2002  Subject Category - Finance.csv',
 'scimagojr 2003  Subject Category - Finance.csv',
 'scimagojr 2004  Subject Category - Finance.csv',
 'scimagojr 2005  Subject Category - Finance.csv',
 'scimagojr 2006  Subject Category - Finance.csv',
 'scimagojr 2007  Subject Category - Finance.csv',
 'scimagojr 2008  Subject Category - Finance.csv',
 'scimagojr 2009  Subject Category - Finance.csv',
 'scimagojr 2010  Subject Category - Finance.csv',
 'scimagojr 2011  Subject Category - Finance.csv',
 'scimagojr 2012  Subject Category - Finance.csv',
 'scimagojr 2013  Subject Category - Finance.csv',
 'scimagojr 2014  Subject Category - Finance.csv',
 'scimagojr 2015  Subject Category - Finance.csv',
 'scimagojr 2016  Subject Category - Finance.csv',
 'scimagojr 2017  Subject Category - Finance.csv',
 'scimagojr 2018  Subject Category - Finance.csv']

### 3. Carga de archvos csv de una ruta

- Se leen los nombres de los archivos, pero esta vez, la lista contiene la ruta y para que el sistema los reconozca.
- Se abren con pandas y se anexan como una lista
- Se concatenan los archivos, para crear un df general con el contenido de toda la información.

In [5]:
all_files = glob.glob(pathf + "/*.csv")

li = []

for filename in all_files:
    print(filename)
    df = pd.read_csv(filename, index_col=None, header=0, sep=';')
    li.append(df)

frame = pd.concat(li, axis=0, ignore_index=True,sort=False)

00_scimago_rank\scimagojr 1999  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2000  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2001  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2002  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2003  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2004  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2005  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2006  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2007  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2008  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2009  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2010  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2011  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2012  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2013  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2014  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2015  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2016  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2017  Subject Category - Finance.csv
00_scimago_rank\scimagojr 2018  Subject Category - Finance.csv

Impresión del encabezado y el final del df

In [6]:
frame.head()

,Rank,Sourceid,Title,Type,Issn,SJR,SJR Quartile,H index,Total Docs. (1999),Total Docs. (3years),Total Refs.,Total Cites (3years),Citable Docs. (3years),Cites / Doc. (2years),Ref. / Doc.,Country,Publisher,Coverage,Categories,Total Docs. (2000),Total Docs. (2001),Total Docs. (2002),Total Docs. (2003),Total Docs. (2004),Total Docs. (2005),Total Docs. (2006),Total Docs. (2007),Total Docs. (2008),Total Docs. (2009),Total Docs. (2010),Total Docs. (2011),Total Docs. (2012),Total Docs. (2013),Total Docs. (2014),Total Docs. (2015),Total Docs. (2016),Total Docs. (2017),Total Docs. (2018)
0,1,24379,Journal of Financial Economics,journal,0304405X,"9,621",Q1,223,55.0,152,1804,581,152,"3,61","32,80",Netherlands,Elsevier BV,1974-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,17500,Journal of Finance,journal,"00221082, 15406261","9,553",Q1,264,77.0,228,2716,983,228,"3,94","35,27",United Kingdom,Blackwell Publishing Inc.,1946-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,16161,Review of Financial Studies,journal,"14657368, 08939454","6,273",Q1,157,40.0,99,1157,209,99,"1,94","28,93",United Kingdom,Oxford University Press,1996-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,28096,Accounting Review,journal,00014826,"4,503",Q1,133,22.0,78,629,226,78,"2,53","28,59",United States,American Accounting Association,1996-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,80370,Journal of Financial and Quantitative Analysis,journal,00221090,"4,380",Q1,101,23.0,79,696,141,79,"1,22","30,26",United Kingdom,Cambridge University Press,1966-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
frame.tail()

,Rank,Sourceid,Title,Type,Issn,SJR,SJR Quartile,H index,Total Docs. (1999),Total Docs. (3years),Total Refs.,Total Cites (3years),Citable Docs. (3years),Cites / Doc. (2years),Ref. / Doc.,Country,Publisher,Coverage,Categories,Total Docs. (2000),Total Docs. (2001),Total Docs. (2002),Total Docs. (2003),Total Docs. (2004),Total Docs. (2005),Total Docs. (2006),Total Docs. (2007),Total Docs. (2008),Total Docs. (2009),Total Docs. (2010),Total Docs. (2011),Total Docs. (2012),Total Docs. (2013),Total Docs. (2014),Total Docs. (2015),Total Docs. (2016),Total Docs. (2017),Total Docs. (2018)
3538,243,21100238636,ATA Journal of Legal Tax Research,journal,1543866X,"0,101",Q4,2,NaN,18,58,1,17,"0,00","19,33",United States,American Accounting Association,"2011, 2014-ongoing",Accounting (Q4); Finance (Q4); Law (Q4),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3539,244,28141,Journal of Taxation,journal,00224863,"0,100",Q4,7,NaN,175,141,2,175,"0,01","5,64",United States,RIA Group,1998-ongoing,Accounting (Q4); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0
3540,245,38885,Real Estate Taxation,journal,00935107,"0,100",Q4,2,NaN,76,0,0,66,"0,00","0,00",United States,RIA Group,1996-ongoing,Accounting (Q4); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3541,246,15666,Banking Law Journal,journal,00055506,NaN,-,5,NaN,0,143,0,0,"0,00","6,22",United States,Sheshunoff Information Services Inc.,"1996-2012, 2018-ongoing","Business, Management and Accounting (miscellan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0
3542,247,21100867420,Pakistan Journal of Commerce and Social Science,journal,"19978553, 23098619",NaN,-,1,NaN,0,3362,0,0,"0,00","73,09",Pakistan,Johar Education Society Pakistan,2018-ongoing,"Business, Management and Accounting (miscellan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0

Descripción del df, se valida que los nombres de las columnas no contengan caracteres especiales como '\n'

In [8]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3543 entries, 0 to 3542
Data columns (total 38 columns):
Rank                      3543 non-null int64
Sourceid                  3543 non-null int64
Title                     3543 non-null object
Type                      3543 non-null object
Issn                      3543 non-null object
SJR                       3338 non-null object
SJR Quartile              3543 non-null object
H index                   3543 non-null int64
Total Docs. (1999)        105 non-null float64
Total Docs. (3years)      3543 non-null int64
Total Refs.               3543 non-null int64
Total Cites (3years)      3543 non-null int64
Citable Docs. (3years)    3543 non-null int64
Cites / Doc. (2years)     3543 non-null object
Ref. / Doc.               3543 non-null object
Country                   3543 non-null object
Publisher                 3543 non-null object
Coverage                  3543 non-null object
Categories                3543 non-null object
Total Docs. (2000)        108 non-null float64
Total Docs. (2001)        113 non-null float64
Total Docs. (2002)        115 non-null float64
Total Docs. (2003)        123 non-null float64
Total Docs. (2004)        128 non-null float64
Total Docs. (2005)        137 non-null float64
Total Docs. (2006)        148 non-null float64
Total Docs. (2007)        156 non-null float64
Total Docs. (2008)        172 non-null float64
Total Docs. (2009)        194 non-null float64
Total Docs. (2010)        200 non-null float64
Total Docs. (2011)        215 non-null float64
Total Docs. (2012)        217 non-null float64
Total Docs. (2013)        220 non-null float64
Total Docs. (2014)        231 non-null float64
Total Docs. (2015)        233 non-null float64
Total Docs. (2016)        233 non-null float64
Total Docs. (2017)        248 non-null float64
Total Docs. (2018)        247 non-null float64
dtypes: float64(20), int64(7), object(11)
memory usage: 1.0+ MB

### Filtro de journals Q1 y Q2 de los datos de scimago

- Se filtran las líneas que contengan Q1 y Q2
- Se copia un df del original
- Se extraen los valores únicos de journals

In [14]:
df = frame[(frame['SJR Quartile']=='Q1') | (frame['SJR Quartile']=='Q2')]

In [15]:
df

,Rank,Sourceid,Title,Type,Issn,SJR,SJR Quartile,H index,Total Docs. (1999),Total Docs. (3years),Total Refs.,Total Cites (3years),Citable Docs. (3years),Cites / Doc. (2years),Ref. / Doc.,Country,Publisher,Coverage,Categories,Total Docs. (2000),Total Docs. (2001),Total Docs. (2002),Total Docs. (2003),Total Docs. (2004),Total Docs. (2005),Total Docs. (2006),Total Docs. (2007),Total Docs. (2008),Total Docs. (2009),Total Docs. (2010),Total Docs. (2011),Total Docs. (2012),Total Docs. (2013),Total Docs. (2014),Total Docs. (2015),Total Docs. (2016),Total Docs. (2017),Total Docs. (2018)
0,1,24379,Journal of Financial Economics,journal,0304405X,"9,621",Q1,223,55.0,152,1804,581,152,"3,61","32,80",Netherlands,Elsevier BV,1974-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,17500,Journal of Finance,journal,"00221082, 15406261","9,553",Q1,264,77.0,228,2716,983,228,"3,94","35,27",United Kingdom,Blackwell Publishing Inc.,1946-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,16161,Review of Financial Studies,journal,"14657368, 08939454","6,273",Q1,157,40.0,99,1157,209,99,"1,94","28,93",United Kingdom,Oxford University Press,1996-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,28096,Accounting Review,journal,00014826,"4,503",Q1,133,22.0,78,629,226,78,"2,53","28,59",United States,American Accounting Association,1996-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,80370,Journal of Financial and Quantitative Analysis,journal,00221090,"4,380",Q1,101,23.0,79,696,141,79,"1,22","30,26",United Kingdom,Cambridge University Press,1966-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,29838,Journal of Accounting and Economics,journal,01654101,"4,031",Q1,132,42.0,68,1098,202,68,"2,49","26,14",Netherlands,Elsevier BV,1979-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,17555,Journal of Monetary Economics,journal,03043932,"4,002",Q1,112,49.0,156,1489,248,155,"1,38","30,39",Netherlands,Elsevier BV,1975-ongoing,Economics and Econometrics (Q1); Finance (Q1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,29857,Journal of Accounting Research,journal,"1475679X, 00218456","3,812",Q1,118,34.0,86,808,181,86,"1,69","23,76",United Kingdom,Blackwell Publishing Inc.,1996-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,24393,Journal of International Economics,journal,00221996,"3,812",Q1,121,55.0,133,1486,257,133,"1,43","27,02",Netherlands,Elsevier BV,1971-ongoing,Economics and Econometrics (Q1); Finance (Q1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,27365,World Bank Economic Review,journal,"1564698X, 02586770","3,747",Q1,79,22.0,63,567,142,63,"1,62","25,77",United Kingdom,Oxford University Press,1986-ongoing,Accounting (Q1); Development (Q1); Economics a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,14194,Games and Economic Behavior,journal,"10902473, 08998256","3,728",Q1,84,63.0,203,1214,170,203,"0,76","19,27",United States,Elsevier Inc.,1989-ongoing,Economics and Econometrics (Q1); Finance (Q1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,28996,Journal of Financial Intermediation,journal,"10960473, 10429573","2,843",Q1,67,12.0,42,366,49,42,"0,70","30,50",United States,Elsevier Inc.,1990-ongoing,Economics and Econometrics (Q1); Finance (Q1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,20749,European Economic Review,journal,00142921,"2,772",Q1,116,88.0,309,1891,438,309,"1,17","21,49",Netherlands,Elsevier BV,1969-ongoing,Economics and Econometrics (Q1); Finance (Q1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,29113,Contemporary Accounting Research,journal,08239150,"2,648",Q1,81,24.0,63,719,106,63,"1,21","29,96",United States,Wiley-Blackwell,1984-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,29009,Journal of Public Economics,journal,00472727,"2,566",Q1,123,79.0,262,2052,275,262,"0,86","25,97",Netherlands,Elsevier BV,1972-ongoing,Economics and Econometrics (Q1); Finance (Q1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,17557,"Journal of Money, Credit and Banking",journal,"15384616, 00222879","2,533",Q1,95,37.0,131,1197,223,131,"1,46","32,35",United States,Wiley-Blackwell,1996-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,20635,Journal of Management,journal,01492063,"2,364",Q1,192,38.0,103,3366,184,99,"1,63","88,58",United States,SAGE Publications,1975-ongoing,Finance (Q1); Strategy and Management (Q1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,18173,Mathematical Finance,journal,"09601627, 14679965","2,329",Q1,68,16.0,56,413,99,56,"1,66","25,81",United Kingdom,Blackwell Publishing Inc.,1991-ongoing,Accounting (Q1); Applied Mathematics (Q1); Eco...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,74502,Financial Management,journal,"1755053X, 00463892","1,760",Q1,59,33.0,80,1129,124,80,"1,73","34,21",United States,Wiley-Blackwell,1996-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,28708,National Tax Journal,journal,00280283,"1,571",Q1,51,47.0,121,1239,82,121,"0,65","26,36",United States,National Tax Association,"1985, 1989, 1995-2014, 2016-ongoing",Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,17496,Journal of Corporate Finance,journal,09291199,"1,491",Q1,83,17.0,39,492,26,39,"0,68","28,94",Netherlands,Elsevier BV,1994-ongoing,Business and International Management (Q1); Ec...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,17528,Journal of Financial Markets,journal,13864181,"1,489",Q1,52,16.0,13,427,12,13,"0,92","26,69",Netherlands,Elsevier BV,1998-ongoing,Economics and Econometrics (Q1); Finance (Q1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23,28062,International Tax and Public Finance,journal,"15736970, 09275940","1,461",Q1,45,28.0,78,751,54,78,"0,61","26,82",Netherlands,Kluwer Academic Publishers,1994-ongoing,Accounting (Q1); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,6400153171,ASTIN Bulletin,journal,"05150361, 17831350","1,430",Q1,36,23.0,66,213,49,66,"0,51","9,26",United Kingdom,Cambridge University Press,"1958-1969, 1971-1975, 1977-1982, 1984-ongoing",Economics and Econometrics (Q1); Finance (Q1);...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,24380,Journal of Financial Research,journal,"02702592, 14756803","1,345",Q1,43,30.0,95,511,76,95,"0,85","17,03",United Kingdom,Blackwell Publishing Inc.,"1978-1995, 2003-ongoing",Finance (Q1); Accounting (Q2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,29401,Journal of the Japanese and International Econ...,journal,"08891583, 10958681","1,154",Q2,36,19.0,64,459,37,64,"0,27","24,16",United States,Elsevier Inc.,1987-ongoing,Political Science and International Relations ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,16159,Review of Derivatives Research,journal,13806645,"0,987",Q2,25,7.0,16,168,7,16,"0,50","24,00",Netherlands,Kluwer Academic Publishers,"1996, 1998-2000, 2002-ongoing","Economics, Econometrics and Finance (miscellan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,17499,Journal of Empirical Finance,journal,09275398,"0,979",Q2,66,23.0,52,730,55,52,"0,85","31,74",Netherlands,Elsevier BV,1993-ongoing,Economics and Econometrics (Q2); Finance (Q2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,29011,Journal of Risk and Uncertainty,journal,"15730476, 08955646","0,975",Q2,65,25.0,87,986,110,87,"1,25","39,44",Netherlands,Kluwer Academic Publishers,1988-ongoing,Accounting (Q2); Economics and Econometrics (Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30,17533,Journal of International Money and Finance,journal,02615606,"0,907",Q2,83,46.0,151,1209,129,150,"0,76","26,28",United Kingdom,Elsevier Ltd.,1982-ongoing,Economics and Econometrics (Q2); Finance (Q2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3391,96,19200156956,Asian Economic Papers,journal,"15360083, 15353516","0,485",Q2,12,NaN,202,490,58,70,"0,73","8,91",United States,MIT Press,2008-ongoing,Economics and Econometrics (Q2); Finance (Q2);...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.0
3392,97,11700154393,Journal of Fixed Income,journal,10598596,"0,480",Q2,12,NaN,82,666,30,70,"0,38","19,03",United States,Institutional Investor Systems,2008-ongoing,Economics and Econometrics (Q2); Finance (Q2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0
3393,98,29806,International Journal of Accounting Informatio...,journal,14670895,"0,478",Q2,44,NaN,54,1549,123,47,"2,65","64,54",United Kingdom,Elsevier Ltd.,2000-ongoing,Accounting (Q2); Finance (Q2); Information Sys...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0
3394,99,11700154334,Journal of Derivatives,journal,10741240,"0,478",Q2,41,NaN,77,555,49,65,"0,49","21,35",United States,Institutional Investor Systems,2008-ongoing,Economics and Econometrics (Q2); Finance (Q2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0
3395,100,16525,Journal of Portfolio Management,journal,00954918,"0,475",Q2,43,NaN,232,1609,157,214,"0,59","19,62",United States,Institutional Investor Systems,1995-ongoing,"Accounting (Q2); Business, Management and Acco...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.0
3396,101,100147314,Journal of International Financial Management ...,journal,"09541314, 1467646X","0,472",Q2,31,NaN,32,710,63,32,"1,61","54,62",United Kingdom,Blackwell Publishing Inc.,"1989-1992, 1994-ongoing","Accounting (Q2); Business, Management and Acco...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0
3397,102,5700168589,Public Budgeting and Finance,journal,02751100,"0,472",Q2,27,NaN,72,870,65,69,"0,72","43,50",United States,Wiley-Blackwell,"1981-1995, 2008-ongoing",Economics and Econometrics (Q2); Finance (Q2);...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0
3398,103,17423,Geneva Papers on Risk and Insurance: Issues an...,journal,"10185895, 14680440","0,461",Q2,28,NaN,100,1501,102,95,"0,71","44,15",Germany,Springer Verlag,1999-ongoing,"Accounting (Q2); Business, Management and Acco...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.0
3399,104,25165,Applied Mathematical Finance,journal,"1350486X, 14664313","0,455",Q2,25,NaN,59,385,43,58,"0,46","20,26",United Kingdom,Chapman & Hall,"1994-1995, 2003-ongoing",Finance (Q2); Applied Mathematics (Q3),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0
3400,105,21100851416,Pacific Accounting Review,journal,"20415494, 01140582","0,453",Q2,17,NaN,59,1621,93,56,"0,71","55,90",United Kingdom,Emerald Group Publishing Ltd.,2017-ongoing,Accounting (Q2); Finance (Q2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0
3401,106,21100262310,EuroMed Journal of Business,journal,14502194,"0,450",Q2,14,NaN,60,1630,124,59,"2,37","70,87",United Kingdom,Emerald Group Publishing Ltd.,"2006, 2014-ongoing","Business, Management and Accounting (miscellan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0
3402,107,145573,GENEVA Risk and Insurance Review,journal,1554964X,"0,450",Q2,19,NaN,26,457,19,24,"0,63","50,78",Germany,Springer Verlag,"1996-2002, 2005-ongoing","Accounting (Q2); Business, Management and Acco...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
3403,108,200147123,Accounting and Finance,journal,08105391,"0,445",Q2,40,NaN,200,5946,313,156,"1,74","46,09",United States,Wiley-Blackwell,1979-ongoing,"Economics, Econometrics and Finance (miscellan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129.0
3404,109,29401,Journal of the Japanese and International Econ...,journal,"08891583, 10958681","0,443",Q2,36,NaN,88,1192,77,86,"0,69","37,25",United States,Elsevier Inc.,1987-ongoing,Economics and Econometrics (Q2); Finance (Q2);...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.0
3405,110,17700156766,Journal of Revenue and Pricing Management,journal,"14766930, 1477657X","0,437",Q2,19,NaN,146,1567,104,131,"0,80","27,49",United Kingdom,Palgrave Macmillan Ltd.,2009-ongoing,Business and International Management (Q2); Ec...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.0
3406,111,69005,Agricultural Finance Review,journal,"00021466, 20416326","0,434",Q2,18,NaN,106,1331,109,97,"1,19","36,97",United Kingdom,Emerald Group Publishing Ltd.,"1980, 2000-ongoing",Agricultural and Biological Sciences (miscella...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.0
3407,112,21100464761,Journal of Risk,journal,"17552842, 14651211","0,427",Q2,8,NaN,78,693,64,78,"0,66","31,50",United States,Incisive Media Ltd.,2011-ongoing,Finance (Q2); Strategy and Management (Q2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0
3408,113,16904,International Finance,journal,"13670271, 14682362","0,424",Q2,35,NaN,49,1031,38,44,"0,55","33,26",United Kingdom,Blackwell Publishing Inc.,1998-ongoing,"Development (Q2); Finance (Q2); Geography, Pla...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.0
3409,114,80174,Annals of Finance,journal,"16142454, 16142446","0,421",Q2,21,NaN,51,938,38,51,"0,68","36,08",Germany,Springer Verlag,2005-ongoing,"Economics, Econometrics and Finance (miscellan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0
3410,115,144657,Journal of Property Investment and Finance,journal,1463578X,"0,421",Q2,30,NaN,115,1430,113,108,"1,11","34,05",United Kingdom,Emerald Group Publishing Ltd.,1999-ongoing,"Business, Management and Accounting (miscellan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0
3411,116,19200157038,International Journal of Sports Marketing and ...,journal,14646668,"0,419",Q2,18,NaN,72,2008,73,64,"1,06","60,85",United Kingdom,Emerald Group Publishing Ltd.,2007-ongoing,Business and International Management (Q2); Fi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.0
3412,117,27748,Emerging Markets Finance and Trade,journal,1540496X,"0,417",Q2,26,NaN,524,10368,547,491,"1,08","43,20",United States,M.E. Sharpe Inc.,2002-ongoing,"Economics, Econometrics and Finance (miscellan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,240.0
3413,118,21100800043,Journal of Hospitality Financial Management,journal,"21522790, 10913211","0,411",Q2,9,NaN,39,201,20,35,"0,54","33,50",United Kingdom,Taylor and Francis Ltd.,2015-ongoing,Finance (Q2); Strategy and Management (Q2); To...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
3414,119,21100199701,Journal of European Real Estate Research,journal,17539269,"0,409",Q2,12,NaN,55,1199,49,49,"0,91","44,41",United Kingdom,Emerald Group Publishing Ltd.,2008-ongoing,Finance (Q2); Accounting (Q3); Economics and E...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0
3415,120,24206,Review of Financial Economics,journal,10583300,"0,408",Q2,34,NaN,84,940,92,77,"1,13","34,81",Netherlands,Elsevier BV,1994-ongoing,Finance (Q2); Economics and Econometrics (Q3),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0
3416,121,29804,International Journal of Accounting,journal,10944060,"0,397",Q2,47,NaN,76,1151,110,70,"1,14","60,58",United Kingdom,Elsevier Ltd.,1996-ongoing,Finance (Q2); Accounting (Q3),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0
3417,122,19900192135,International Review of Finance,journal,"14682443, 1369412X","0,397",Q2,14,NaN,84,2129,73,77,"0,89","22,18",United Kingdom,John Wiley & Sons Ltd.,2011-ongoing,Finance (Q2); Economics and Econometrics (Q3),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.0
3418,123,19300156920,International Journal of Sport Finance,journal,"15586235, 1930076X","0,383",Q2,19,NaN,66,764,61,60,"0,63","38,20",United States,Fitness Information Technology,2008-ongoing,Business and International Management (Q2); Fi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0
3419,124,21100410629,"Intelligent Systems in Accounting, Finance and...",journal,10991174,"0,377",Q2,5,NaN,43,576,41,40,"1,19","41,14",United Kingdom,John Wiley and Sons Ltd,2015-ongoing,"Business, Management and Accounting (miscellan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0
3420,125,11200153526,Studies in Economics and Finance,journal,10867376,"0,368",Q2,15,NaN,93,1566,87,93,"0,81","47,45",United Kingdom,Emerald Group Publishing Ltd.,2008-ongoing,"Economics, Econometrics and Finance (miscellan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.0

In [16]:
df['Title'].unique()

array(['Journal of Financial Economics', 'Journal of Finance',
       'Review of Financial Studies', 'Accounting Review',
       'Journal of Financial and Quantitative Analysis',
       'Journal of Accounting and Economics',
       'Journal of Monetary Economics', 'Journal of Accounting Research',
       'Journal of International Economics', 'World Bank Economic Review',
       'Games and Economic Behavior',
       'Journal of Financial Intermediation', 'European Economic Review',
       'Contemporary Accounting Research', 'Journal of Public Economics',
       'Journal of Money, Credit and Banking', 'Journal of Management',
       'Mathematical Finance', 'Financial Management',
       'National Tax Journal', 'Journal of Corporate Finance',
       'Journal of Financial Markets',
       'International Tax and Public Finance', 'ASTIN Bulletin',
       'Journal of Financial Research',
       'Journal of the Japanese and International Economies',
       'Review of Derivatives Research', 'Journal of Empirical Finance',
       'Journal of Risk and Uncertainty',
       'Journal of International Money and Finance',
       'Journal of Real Estate Finance and Economics',
       'Journal of Derivatives', 'Journal of Portfolio Management',
       'Real Estate Economics', 'Financial Analysts Journal',
       'Economics Letters', 'Journal of Banking and Finance',
       'International Review of Law and Economics',
       'Journal of World Business', 'International Finance',
       'Journal of Futures Markets', 'World Economy',
       'China Economic Review', 'Critical Perspectives on Accounting',
       'Fiscal Studies', 'Management Accounting Research',
       'International Journal of Finance and Economics', 'Auditing',
       'Long Range Planning', 'Pacific Basin Finance Journal',
       'Japan and the World Economy',
       'Journal of Accounting, Auditing and Finance',
       'Journal of Risk and Insurance',
       'Journal of Public Economic Theory',
       'GENEVA Risk and Insurance Review',
       'Journal of Financial Services Research',
       'Journal of International Management',
       'Journal of International Financial Markets, Institutions and Money',
       'Accounting and Finance', 'Quantitative Finance',
       'Venture Capital', 'International Business Review',
       'Decisions in Economics and Finance',
       'Journal of Property Investment and Finance',
       'Journal of International Financial Management and Accounting',
       'Review of Finance',
       'North American Journal of Economics and Finance',
       'Family Business Review', 'Journal of Risk Finance',
       'Journal of Pension Economics and Finance',
       'Agricultural Finance Review', 'Financial Review',
       'Journal of Asian Economics',
       'Financial Markets, Institutions and Instruments',
       'International Journal of Health Care Finance and Economics',
       'Journal of the American Taxation Association',
       'Finance and Stochastics', 'Finance Research Letters',
       'International Journal of Accounting Information Systems',
       'Annals of Economics and Finance',
       'Journal of Financial Econometrics',
       'American Law and Economics Review',
       'International Journal of Theoretical and Applied Finance',
       'Journal of Business Finance and Accounting',
       'Review of Financial Economics',
       'International Review of Economics and Finance',
       'Emerging Markets Finance and Trade', 'Annals of Finance',
       'Financial History Review', 'Foundations and Trends in Accounting',
       'Applied Mathematical Finance', 'Applied Financial Economics',
       'Journal of Financial Stability', 'Accounting Forum',
       'Journal of Multinational Financial Management',
       'Mathematics and Financial Economics',
       'Technological and Economic Development of Economy',
       'Journal of International Accounting, Auditing and Taxation',
       'Journal of Corporate Real Estate',
       'Review of Quantitative Finance and Accounting',
       'Financial Markets and Portfolio Management',
       'Risk Management and Insurance Review',
       'Research in International Business and Finance',
       'International Review of Financial Analysis',
       'Geneva Papers on Risk and Insurance: Issues and Practice',
       'International Review of Environmental and Resource Economics',
       'International Journal of Accounting',
       'International Journal of Revenue Management',
       'International Journal of Banking, Accounting and Finance',
       'Public Finance Review', 'Research in Accounting Regulation',
       'Property Management', 'Annual Review of Financial Economics',
       'SIAM Journal on Financial Mathematics',
       'International Journal of Sport Finance',
       'International Journal of Central Banking',
       'Asian Economic Papers', 'Journal of Fixed Income',
       'Review of Pacific Basin Financial Markets and Policies',
       'Journal of Financial Counseling and Planning',
       'International Journal of Sports Marketing and Sponsorship',
       'Quarterly Review of Economics and Finance',
       'International Journal of Digital Accounting Research',
       'Journal of Revenue and Pricing Management',
       'Public Budgeting and Finance', 'Accounting in Europe',
       'Journal of Alternative Investments',
       'International Review of Finance', 'Journal of Education Finance',
       'Journal of Behavioral Finance',
       'Journal of Computational Finance', 'Risk Management',
       'Global Finance Journal', 'Journal of Credit Risk', 'FinanzArchiv',
       'Review of Development Finance', 'Journal of Risk',
       'Journal of European Real Estate Research',
       'Economie Internationale', 'Investment Analysts Journal',
       'Finance a Uver', 'Journal of Behavioral and Experimental Finance',
       'Borsa Istanbul Review', 'Review of Behavioral Finance',
       'Journal of Banking Regulation',
       'International Journal of Islamic and Middle Eastern Finance and Management',
       'Intelligent Systems in Accounting, Finance and Management',
       'Studies in Economics and Finance', 'Journal of Commodity Markets',
       'Quarterly Journal of Finance',
       'Journal of Sustainable Finance and Investment',
       'Voprosy Ekonomiki', 'Pacific Accounting Review',
       'EuroMed Journal of Business',
       'Journal of Hospitality Financial Management'], dtype=object)

In [17]:
len(df['Title'].unique())

155

In [18]:
df['Issn'].unique()

array(['0304405X', '00221082, 15406261', '14657368, 08939454', '00014826',
       '00221090', '01654101', '03043932', '1475679X, 00218456',
       '00221996', '1564698X, 02586770', '10902473, 08998256',
       '10960473, 10429573', '00142921', '08239150', '00472727',
       '15384616, 00222879', '01492063', '09601627, 14679965',
       '1755053X, 00463892', '00280283', '09291199', '13864181',
       '15736970, 09275940', '05150361, 17831350', '02702592, 14756803',
       '08891583, 10958681', '13806645', '09275398', '15730476, 08955646',
       '02615606', '1573045X, 08955638', '10741240', '00954918',
       '15406229, 10808620', '0015198X', '01651765', '03784266',
       '01448188', '10909516', '13670271, 14682362', '10969934, 02707314',
       '03785920, 14679701', '1043951X', '10452354, 10959955',
       '01435671, 14755890', '10445005, 10961224', '10991158, 10769307',
       '02780380', '00246301', '0927538X', '09221425', '0148558X',
       '15396975, 00224367', '14679779, 10973923', '1554964X',
       '15730735, 09208550', '10754253', '10424431', '08105391',
       '14697696, 14697688', '14645343, 13691066', '09695931', '15938883',
       '1463578X', '09541314, 1467646X', '15723097', '10629408',
       '08944865', '09657967, 15265943', '14747472', '00021466, 20416326',
       '15406288, 07328516', '10490078', '09638008, 14680416',
       '13896563, 15736962', '15588017, 01989073', '14321122, 09492984',
       '15446131, 15446123', '14670895', '15297373', '14798409',
       '14657252', '02190249', '0306686X', '10583300', '10590560',
       '1540496X', '16142454, 16142446', '09685650, 14740052', '15540642',
       '1350486X, 14664313', '09603107, 14664305', '15723089', '01559982',
       '1042444X', '18629679', '20294921, 20294913', '10619518',
       '1463001X', '0924865X, 15737179', '1555497X, 15554961',
       '15406296, 10981616', '02755319', '10575219', '10185895, 14680440',
       '19321465, 19321473', '10944060', '14747332, 17418186',
       '17553830, 17553849', '10911421', '10520457', '02637472',
       '19411367', '1945497X', '15586235, 1930076X', '18154654',
       '15360083, 15353516', '10598596', '02190915', '10523073',
       '14646668', '10629769', '15778517', '14766930, 1477657X',
       '02751100', '17449499, 17449480', '15203255', '14682443, 1369412X',
       '00989495', '15427579, 15427560', '14601559, 17552850',
       '17434637, 14603799', '10440283', '17559723, 17446619',
       '00152218, 16140974', '18799337', '17552842, 14651211', '17539269',
       '12408093, 17775582', '10293523', '24647683, 00151920',
       '22146350, 22146369', '22148469', '19405987, 19405979',
       '17502071, 17456452', '17538394, 17538408', '10991174', '10867376',
       '24058513', '20101406, 20101392', '20430809, 20430795', '00428736',
       '20415494, 01140582', '14502194', '21522790, 10913211'],
      dtype=object)

In [19]:
len(df['Issn'].unique())

155

In [31]:
descarga = pd.DataFrame(df['Issn'].unique(), columns = ['Issn'])
descarga.to_csv('isin.csv',index=False )